shortenersite/urls.py
from django.conf.urls import url

from . import views


app_name = 'shortenersite'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='home'),

	url(r'^all/$', views.UrlsListView.as_view(), name='listall'),

	url(r'^(?P<short_id>\w{6})$', views.redirect_original, name='redirectoriginal'),

	url(r'^details/(?P<pk>\w{6})$', views.DetailView.as_view(), name='details'),

	url(r'^delete/(?P<pk>\w{6})$', views.DeleteView.as_view(), name='delete_url'),

	url(r'^makeshort/$', views.shorten_url, name='shortenurl'),
]

urlshortener/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', admin.site.urls),

	url(r'', include('shortenersite.urls')),
]

shortenersite/models.py
from __future__ import unicode_literals

from django.db import models

class Urls(models.Model):
	short_id = models.SlugField(max_length = 6, primary_key = True)
	httpurl = models.URLField(max_length = 200)
	pub_date = models.DateTimeField(auto_now_add = True)
	count = models.IntegerField(default = 0)

	def __str__(self):
		return self.httpurl

	def get_absolute_url(self):
		from django.urls import reverse
		return reverse('shortenersite:details', kwargs={'pk': self.short_id})

	class Meta:
		ordering = ["-count", "-pub_date"]

shortenersite/views.py
from django.shortcuts import render_to_response, get_object_or_404, render, redirect
import random, string, json
from shortenersite.models import Urls
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.template.context_processors import csrf
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views import generic
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.views.decorators.cache import cache_page


CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)


@method_decorator(csrf_protect, name='dispatch')
class IndexView(generic.ListView):
	template_name = 'shortenersite/index.html'
	context_object_name = 'popular_urls'

	def get_queryset(self):
		"""Return the most popular 20 urls."""
		return Urls.objects.all()[:20]

@method_decorator(cache_page(CACHE_TTL), name='dispatch')
class DetailView(generic.DetailView):
	model = Urls
	context_object_name = 'current_url'
	template_name = 'shortenersite/details.html'

@cache_page(CACHE_TTL)
def redirect_original(request, short_id):
	url = get_object_or_404(Urls, pk = short_id)
	url.count += 1
	url.save()
	return HttpResponseRedirect(url.httpurl)

def shorten_url(request):
	url = request.POST.get("url", '')

	if url == '':
		from django.contrib import messages
		messages.warning(request, "Url field is empty. Nothing to shorten.")
		return redirect('shortenersite:home')

	short_id = get_short_code()
	b = Urls(httpurl = url, short_id = short_id)
	b.save()

	return redirect(b)

def get_short_code():
	length = Urls._meta.get_field('short_id').max_length
	char = string.ascii_uppercase + string.digits + string.ascii_lowercase

	# if the randomly generated short_id is used then generate next
	while True:
		short_id = ''.join(random.choice(char) for x in range(length))
		try:
			temp = Urls.objects.get(pk = short_id)
		except:
			return short_id

@method_decorator(csrf_protect, name='dispatch')
class UrlsListView(generic.ListView):
	context_object_name = 'urls'
	template_name = 'shortenersite/all.html'

	def get_queryset(self):
		urls = Urls.objects.all()
		paginator = Paginator(urls, 10)
		page = self.request.GET.get('page')

		try:
			urls = paginator.page(page)
		except PageNotAnInteger:
			urls = paginator.page(1)
		except EmptyPage:
			urls = paginator.page(paginator.num_pages)

		return urls


class DeleteView(generic.DeleteView):
	model = Urls
	success_url = reverse_lazy('shortenersite:listall')

shortenersite/templates/shortenersite/all.html
{% extends "shortenersite/base.html" %}

{% block title %}URL Shortner - Make your URL shorter!{% endblock %}

{% block subheader %}Saved urls{% endblock %}

{% block content %}

{% if urls %}
<table class="table table-striped">
	<thead>
		<tr>
			<th>Shortcut</th>
			<th>Urls</th>
			<th>Popularity</th>
			<th>Added</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		{% for url in urls %}
		<tr>
			<td><a href="{% url 'shortenersite:details' pk=url.short_id %}">{{ url.short_id }}</a></td>
			<td><a href="{% url 'shortenersite:redirectoriginal' short_id=url.short_id %}">{{ url.httpurl }}</a></td>
			<td>{{ url.count }}</td>
			<td>{{ url.pub_date }}</td>
			<td>
				<form action="{% url 'shortenersite:delete_url' pk=url.short_id %}" method="post">
					{% csrf_token %}
					<input type="submit" value="Delete" class="btn" onclick="return confirm('Are you sure?');">
				</form>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

<ul class="pagination">
	{% if urls.has_previous %}
	<li><a href="?page={{ urls.previous_page_number }}">&larr; Previous</a></li>
	{% endif %}

	<li class="disabled"><a href="#">Page {{ urls.number }} of {{ urls.paginator.num_pages }}</a></li>

	{% if urls.has_next %}
	<li><a href="?page={{ urls.next_page_number }}">Next &rarr;</a></li>
	{% endif %}
</ul>

{% else %}
<div class="well">
	<em>Nothing to display</em>
</div>
{% endif %}

{% endblock %}

shortenersite/templates/shortenersite/base.html
<!DOCTYPE html>
<html>
<head>
 <title>{% block title %}{% endblock %}</title>
 {% load staticfiles %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
 <link rel="stylesheet" type="text/css" href="{% static 'shortenersite/css/custom.css' %}" />
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
 <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
<div id="wrap">

<nav class="navbar navbar-default">
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	  <ul class="nav navbar-nav navbar-right">
		<li {% ifequal request.path "/" %}class="active"{% endifequal %}><a href="{% url 'shortenersite:home' %}">Home</a></li>
		<li {% ifequal request.path "/all/" %}class="active"{% endifequal %}><a href="{% url 'shortenersite:listall' %}">All</a></li>
	  </ul>
  </div>
</nav>

<header>
 <h1><a href="{% url 'shortenersite:home' %}">URL Shortener</a><br/><small>{% block subheader %}Shorten the URL{% endblock %}</small></h1>
</header>

<div id="content">
{% block content %}

{% endblock %}
</div>
</div>
</body>
</html>

shortenersite/templates/shortenersite/details.html
{% extends "shortenersite/base.html" %}

{% block title %}URL Shortner - {{ SITE_URL }}{{ current_url.short_id }}{% endblock %}

{% block subheader %}{{ SITE_URL }}{{ current_url.short_id }}{% endblock %}

{% block content %}

<table class="table table-striped">
	<tbody>
		<tr><td><strong>Shortcut</strong></td><td>{{ SITE_URL }}{{ current_url.short_id }}</td></tr>
		<tr><td><strong>Link</strong></td>
			<td><a href="{% url 'shortenersite:redirectoriginal' short_id=current_url.short_id %}">{{ current_url.httpurl }}</a></td>
		</tr>
		<tr><td><strong>Popularity</strong></td><td>{{ current_url.count }}</td></tr>
		<tr><td><strong>Added</strong></td><td>{{ current_url.pub_date }}</td></tr>
	</tbody>
</table>

<a href="{% url 'shortenersite:home' %}" class="btn btn-info" role="button">Add another</a>

<form action="{% url 'shortenersite:delete_url' pk=current_url.short_id %}" method="post" class="pull-right">
	{% csrf_token %}
	<input type="submit" value="Delete" class="btn" onclick="return confirm('Are you sure?');">
</form>

{% endblock %}

shortenersite/templates/shortenersite/index.html
{% extends "shortenersite/base.html" %}

{% block title %}URL Shortner - Make your URL shorter!{% endblock %}

{% block content %}

<div class="panel panel-default">
	<div class="panel-body">
	<form action="{% url 'shortenersite:shortenurl' %}" method="post">
		{% csrf_token %}
		<div class="col-sm-9">
		<input type="text" name="url" id="url" class="form-control input-sm" placeholder="Your url here" />
		</div>
		<div class="col-sm-3">
		<input type="submit" value="Submit" class="btn btn-primary" />
		</div>
	</form>
	</div>

	{% if messages %}
		{% for message in messages %}
		<div class="panel-footer url-result-error"><span id="url-result">{{ message }}</span></div>
		{% endfor %}
	{% elif short_url %}
	<div class="panel-footer url-result"><span id="url-result">{{ short_url }}</span></div>
	{% else %}
	<div class="panel-footer url-result"><span id="url-result">Enter the URL above and click submit!</span></div>
	{% endif %}
</div>

{% if popular_urls %}

<header>
 <h1><small>Popular Links</small></h1>
</header>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Shortcut</th>
			<th>Urls</th>
			<th>Popularity</th>
			<th>Added</th>
		</tr>
	</thead>
	<tbody>
		{% for url in popular_urls %}
		<tr>
			<td><a href="{% url 'shortenersite:details' pk=url.short_id %}">{{ url.short_id }}</a></td>
			<td><a href="{% url 'shortenersite:redirectoriginal' short_id=url.short_id %}">{{ url.httpurl }}</a></td>
			<td>{{ url.count }}</td>
			<td>{{ url.pub_date }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endif %}

{% endblock %}